name:                board-app
version:             0.1.0.0
github:              "githubuser/board-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/board-app#readme>

dependencies:
- base >= 4.7 && < 5
- servant >= 0.13 && < 0.14
- servant-server >= 0.13 && < 0.14
- mtl >= 2.1 && < 2.3
- transformers >= 0.3 && < 0.6
- aeson >= 1.2.3.0 && < 1.3
- text >= 1.2.3.0 && < 1.3
- bytestring >= 0.10.4.0 && < 0.11
- wai >= 3.0 && < 3.3
- wai-app-static
- http-types
- warp >= 3.0 && < 3.3
- persistent >= 2.8.0 && < 2.9
- persistent-template >= 2.5.0 && < 2.6.0
- persistent-postgresql
- monad-logger

library:
  source-dirs: src

executables:
  board-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - board-app

tests:
  board-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - board-app
